# Generated by Django 2.2.17 on 2021-01-24 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='fullname',
            new_name='bookname',
        ),
    ]
